fix: accept `cli-version` as input and fire exit code if next block version is not found

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -39,6 +39,9 @@ inputs:
     description: "The git token from secrets to use when tagging the git repo upon successful block push"
     required: false
     default: ${{ github.token }}
+  cli-version:
+    description: "Optional: pull cli from specified tag. Default: release"
+    default: 1.0.0-beta.44
 
 outputs:
   block-version:
@@ -62,7 +65,7 @@ runs:
         client-id: ${{ inputs.client-id }}
         shared-secret: ${{ inputs.shared-secret }}
         command: push block ${{ inputs.block-id }} ${{ inputs.image-uri }} ${{ github.ref_name }}${{ inputs.auto-release == 'true' && ' --release' || '' }} --provider Github --repository-url ${{ github.server_url }}/${{ github.repository }}.git --commit-id ${{ github.sha }} --commit-message "${{ github.event.head_commit.message }}" --commit-datetime ${{ github.event.head_commit.timestamp }} --author-email ${{ github.event.head_commit.author.email }} --committer-email ${{ github.event.head_commit.committer.email }}
-        cli-version: 1.0.0-beta.44
+        cli-version: ${{ inputs.cli-version }}
         cli-splash: true
 
     - name: Set output variables
@@ -71,6 +74,10 @@ runs:
       run: |
         VERSION_NO=$(echo -e ${{ steps.cli.outputs.command-output }} | jq .version.versionNo)
         echo "Setting block-version: $VERSION_NO"
+        if [ -z "$VERSION_NO" ]; then
+          echo "Error Next block version was not created"
+          exit 1
+        fi
         echo "block-version=$VERSION_NO" >> $GITHUB_OUTPUT
 
     - uses: actions/checkout@v3
